## ASSIGNMENT 4

1. Write a function safe_divide(a, b) that divides two numbers and handles ZeroDivisionError and
TypeError separately, printing an appropriate message for each. Use a finally block to print
'Operation attempted.' regardless of the outcome. Test it with valid numbers, division by zero, and a
string input.

In [2]:
def safe_divide(a, b):
    try:
        c = a / b
        print("Result:", c)

    except ZeroDivisionError:
        print("Number cannot divide by zero ")

    except TypeError:
        print("Invalid data type ")

    finally:
        print("Operation attempted")

In [3]:
safe_divide(12,2)

Result: 6.0
Operation attempted


In [5]:
safe_divide(10,0)

Number cannot divide by zero 
Operation attempted


In [7]:
safe_divide(12,'t')

Invalid data type 
Operation attempted


2. Write a function validate_age(age) that raises a custom exception InvalidAgeError (a class you
define, inheriting from Exception) if age is negative or greater than 120. Catch this exception in a
calling block and print a user-friendly message. Test it with at least 3 different values.

In [18]:
class InvalidAgeError(Exception):
    pass


def validate_age(age):
    if age < 0 or age > 120:
        raise InvalidAgeError(
            "Age must be between 0 and 120."
        )
    print(f"Valid age: {age}")


# Test Cases
ages = [25, -5, 130]

for age in ages:
    try:
        validate_age(age)
    except InvalidAgeError as e:
        print("Invalid Age:", e)

Valid age: 25
Invalid Age: Age must be between 0 and 120.
Invalid Age: Age must be between 0 and 120.


3. Write a program that repeatedly asks the user (use a loop with at least 3 simulated inputs in a list,
e.g. user_inputs = ['10', 'abc', '0', '5']) to enter a number and divide 100 by it. Handle the following in
a single try block using multiple except clauses:
a) ValueError if the input is not a number.
b) ZeroDivisionError if the input is zero.
c) A generic Exception as a catch-all for anything else.
Print the result if successful, otherwise print which error occurred.

In [28]:
user_inputs = ['10', 'abc', '0', '5']

for i in user_inputs:
    try:
        num = int(i)
        result = 100 / num
        print("Result :" , result)

    except ValueError:
        print("Given number is not a valid number.")

    except ZeroDivisionError:
        print("Number cannot divide by zero.")

    except Exception as e:
        print(e)

Result : 10.0
Given number is not a valid number.
Number cannot divide by zero.
Result : 20.0


4. Create a 1D NumPy array of integers from 1 to 20. Perform the following:
a) Reshape it into a 4x5 2D array.
b) Print the sum of each row and each column.
c) Extract all elements greater than 10 using boolean indexing.
d) Replace all even numbers in the array with -1.

In [29]:
import numpy as np

In [31]:
# Create array from 1 to 20
a = np.arange(1, 21)

print("Original array:")
print(a)

# a) Reshape into 4x5
a_2d = a.reshape(4, 5)

print("\n 4x5 Array:")
print(a_2d)

# b) Row sums and column sums
print("\n Row sums:")
print(a_2d.sum( axis=1 ))

print("\n Column sums:")
print(a_2d.sum( axis=0 ))

# c) Elements greater than 10
print("\n Elements gretaer than 10:")
print(a[a > 10])

# d) Replace even numbers with -1
new_a = a.copy()
new_a[new_a % 2 == 0] = -1

print("\n Even numbers replaced with -1:")
print(new_a)

Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

 4x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

 Row sums:
[15 40 65 90]

 Column sums:
[34 38 42 46 50]

 Elements gretaer than 10:
[11 12 13 14 15 16 17 18 19 20]

 Even numbers replaced with -1:
[ 1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19 -1]


5. Create two NumPy arrays A and B as shown below and perform:
A = np.array([[1, 2], [3, 4]]) B = np.array([[5, 6], [7, 8]])
a) Element-wise addition, subtraction, and multiplication.
b) Matrix multiplication using np.dot() or the @ operator.
c) Transpose of A.
d) The determinant and inverse of A using np.linalg.

In [34]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# a) Element-wise addition ,subtraction, and multiplication.

print("Addition:")
print(A + B)

print("\n Subtraction:")
print(A - B)

print("\n Multiplication:")
print(A * B)

# b) Matrix multiplication using np.dot() or the @ operator. 

print("\n Matrix Multiplication:")
print(np.dot(A, B))

# c) Transpose of A.

print("\n Transpose of A:")
print(A.T)

# d) Determinant and Inverse of A using np.linalg.

print("\n Determinant of A:")
print(np.linalg.det(A))

print("\n Inverse of A:")
print(np.linalg.inv(A))

Addition:
[[ 6  8]
 [10 12]]

 Subtraction:
[[-4 -4]
 [-4 -4]]

 Multiplication:
[[ 5 12]
 [21 32]]

 Matrix Multiplication:
[[19 22]
 [43 50]]

 Transpose of A:
[[1 3]
 [2 4]]

 Determinant of A:
-2.0000000000000004

 Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]


6. Generate a NumPy array of 15 random integers between 1 and 100 using np.random.randint()
(set a seed of 42 for reproducibility). Then:
a) Find the mean, median, standard deviation, min, and max.
b) Sort the array in descending order.
c) Find the indices of the 3 largest values using np.argsort().
d) Normalize the array so all values lie between 0 and 1.

In [42]:
np.random.seed(42)

arr = np.random.randint(1, 101, 15)

print("Random Array:")
print(arr)

# a) Find the mean, median, standard deviation, min, and max.

print("\nMean:", np.mean(arr))
print("Median:", np.median(arr))
print("Std Dev:", np.std(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))

# b) Sort the array in descending order.

des = np.sort(arr)[::-1]
print("\n Descending Order:")
print(des)

# Find the indices of the 3 largest values using np.argsort(). 

indices = np.argsort(arr)[-3:]
print("\n Indices of 3 Largest Values:")
print(indices)

# d) Normalize the array so all values lie between 0 and 1.

norm= (arr - arr.min()) / (arr.max() - arr.min())

print("\n Normalized Array:")
print(norm)

Random Array:
[ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22]

Mean: 58.06666666666667
Median: 72.0
Std Dev: 31.4843170836247
Min: 3
Max: 100

 Descending Order:
[100  93  88  87  83  75  75  72  61  52  24  22  21  15   3]

 Indices of 3 Largest Values:
[10  1 11]

 Normalized Array:
[0.50515464 0.92783505 0.12371134 0.71134021 0.59793814 0.18556701
 0.82474227 0.86597938 0.74226804 0.74226804 0.87628866 1.
 0.21649485 0.         0.19587629]


7. Create a Pandas DataFrame from the dictionary below and perform the following:
data = { "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"], "Age": [23, 21,
25, 22, 24], "Department": ["AI", "Data Science", "AI", "Web Dev", "Data
Science"], "Score": [88, 92, 79, 95, 67], }
a) Display the first 3 rows and the data types of each column.
b) Add a new column Grade based on Score (>=90 'A', >=75 'B', else 'C').
c) Sort the DataFrame by Score in descending order.
d) Filter rows where Department is 'AI'.

In [43]:
import pandas as pd

In [49]:
data = {
    "Name": ["Aarav", "Priya", "Karan", "Meera", "Sahil"],
    "Age": [23, 21, 25, 22, 24],
    "Department": ["AI", "Data Science", "AI", "Web Dev", "Data Science"],
    "Score": [88, 92, 79, 95, 67]
}

df = pd.DataFrame(data)

# a) First 3 rows and data types of each column 
print("First 3 rows :")
print(df.head(3))

print("\nData Types :")
print(df.dtypes)

# b) Add a new column Grade based on Score (>=90 'A', >=75 'B', else 'C').

grades = []

for i in df["Score"]:
    if i >= 90:
        grades.append("A")
    elif i >= 75:
        grades.append("B")
    else:
        grades.append("C")

df["Grade"] = grades

print("\nDataFrame with new Grade column :")
print(df)

# c) Sort the DataFrame by Score in descending order.

sort_df = df.sort_values(by="Score" , ascending = False)

print("\nSorted by score:")
print(sort_df)

# d) Filter rows where Department is 'AI'.

ai_df = df[df["Department"] == "AI"]

print("\nAI Departments :")
print(ai_df)

First 3 rows :
    Name  Age    Department  Score
0  Aarav   23            AI     88
1  Priya   21  Data Science     92
2  Karan   25            AI     79

Data Types :
Name          object
Age            int64
Department    object
Score          int64
dtype: object

DataFrame with new Grade column :
    Name  Age    Department  Score Grade
0  Aarav   23            AI     88     B
1  Priya   21  Data Science     92     A
2  Karan   25            AI     79     B
3  Meera   22       Web Dev     95     A
4  Sahil   24  Data Science     67     C

Sorted by score:
    Name  Age    Department  Score Grade
3  Meera   22       Web Dev     95     A
1  Priya   21  Data Science     92     A
0  Aarav   23            AI     88     B
2  Karan   25            AI     79     B
4  Sahil   24  Data Science     67     C

AI Departments :
    Name  Age Department  Score Grade
0  Aarav   23         AI     88     B
2  Karan   25         AI     79     B


8. Using the same DataFrame from Q7:
a) Group by Department and find the average Score for each.
b) Find the row with the highest Score using idxmax().
c) Rename the column Score to Marks.
d) Drop the Age column and display the resulting DataFrame

In [55]:
# a) Group by Department and find the average Score for each.

gb= df.groupby("Department")
gb["Score"].mean()

print("Average Score by Department:")
print(avg_score)

# b) Find the row with the highest Score using idxmax()

highest_row = df.loc[df["Score"].idxmax()]

print("\nHighest score row:")
print(highest_row)

# c) Rename the column Score to Marks. 

df_rename = df.rename(columns={"Score": "Marks"})

print("\nRenamed Column:")
print(df_rename)

# d) Drop the Age column and display the resulting DataFrame

new_df = df.drop(columns=["Age"])

print("\nDataFrame without Age:")
print(new_df)

Average Score by Department:
Department
AI              83.5
Data Science    79.5
Web Dev         95.0
Name: Score, dtype: float64

Highest score row:
Name            Meera
Age                22
Department    Web Dev
Score              95
Grade               A
Name: 3, dtype: object

Renamed Column:
    Name  Age    Department  Marks Grade
0  Aarav   23            AI     88     B
1  Priya   21  Data Science     92     A
2  Karan   25            AI     79     B
3  Meera   22       Web Dev     95     A
4  Sahil   24  Data Science     67     C

DataFrame without Age:
    Name    Department  Score Grade
0  Aarav            AI     88     B
1  Priya  Data Science     92     A
2  Karan            AI     79     B
3  Meera       Web Dev     95     A
4  Sahil  Data Science     67     C


9. Create a DataFrame with some missing values as shown below and handle them:
import numpy as np data = { "Product": ["Pen", "Notebook", "Eraser",
"Sharpener", "Ruler"], "Price": [10, np.nan, 5, 8, np.nan], "Stock": [100, 50,
np.nan, 30, 20], }
a) Check the number of missing values in each column using isnull().sum().
b) Fill missing Price values with the column mean.
c) Drop rows where Stock is still missing.
d) Save the cleaned DataFrame to a CSV file named cleaned_products.csv without the index

In [59]:
data = {
    "Product": ["Pen", "Notebook", "Eraser", "Sharpener", "Ruler"],
    "Price": [10, np.nan, 5, 8, np.nan],
    "Stock": [100, 50, np.nan, 30, 20]
}

df = pd.DataFrame(data)

# a) Check the number of missing values in each column using isnull().sum().

print("Missing values :")
print(df.isnull().sum())

# b) Fill missing Price values with the column mean.

cm = df["Price"].mean()

df["Price"] = df["Price"].fillna(cm)

# c) Drop rows where Stock is still missing.

new_df = df.dropna(subset=["Stock"])

print("\nNew clean DataFrame:")
print(new_df)

# d) d) Save the cleaned DataFrame to a CSV file named cleaned_products.csv without the index

new_df.to_csv("cleaned_products.csv", index=False)

print("\nFile is saved as cleaned_products.csv ")

Missing values :
Product    0
Price      2
Stock      1
dtype: int64

New clean DataFrame:
     Product      Price  Stock
0        Pen  10.000000  100.0
1   Notebook   7.666667   50.0
3  Sharpener   8.000000   30.0
4      Ruler   7.666667   20.0

File is saved as cleaned_products.csv 


10. Read the CSV file created in Q9 (cleaned_products.csv) back into a new DataFrame and:
a) Print its shape and column names.
b) Add a new column Total_Value as Price multiplied by Stock.
c) Use describe() to print summary statistics of the numeric columns.
d) Wrap the file reading step in a try-except block to handle the case where the file does not
exist (FileNotFoundError)

In [61]:
try:
    df = pd.read_csv("cleaned_products.csv")

    # a) Print its shape and column names
    
    print("Shape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns)

    # b) Add a new column Total_Value as Price multiplied by Stock.
    
    df["Total_Value"] = (df["Price"] * df["Stock"])

    print("\nDataFrame with Total_Value:")
    print(df)

    # c) Use describe() to print summary statistics of the numeric columns
    
    print("\nSummary statistics:")
    print(df.describe())

except FileNotFoundError:
    print("cleaned_products.csv file not found.")

Shape:
(4, 3)

Columns:
Index(['Product', 'Price', 'Stock'], dtype='object')

DataFrame with Total_Value:
     Product      Price  Stock  Total_Value
0        Pen  10.000000  100.0  1000.000000
1   Notebook   7.666667   50.0   383.333333
2  Sharpener   8.000000   30.0   240.000000
3      Ruler   7.666667   20.0   153.333333

Summary statistics:
           Price       Stock  Total_Value
count   4.000000    4.000000     4.000000
mean    8.333333   50.000000   444.166667
std     1.122167   35.590261   382.500303
min     7.666667   20.000000   153.333333
25%     7.666667   27.500000   218.333333
50%     7.833333   40.000000   311.666667
75%     8.500000   62.500000   537.500000
max    10.000000  100.000000  1000.000000
