## NumPy (numeriacal python)

In [4]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [6]:
# Creating Arrays

In [7]:
sample_array = np.array([1,2,3,4])

In [8]:
sample_array

array([1, 2, 3, 4])

In [10]:
sample_array1  = np.array([10,20,30,40,50,60,70,80,90,100])

In [11]:
print(sample_array1)

[ 10  20  30  40  50  60  70  80  90 100]


In [13]:
# 2D Array (matrix) with 2 rows and 2 columns

In [15]:
sample_array_2 = np.array([[1,2],[3,4]])

In [16]:
sample_array_2

array([[1, 2],
       [3, 4]])

In [20]:
sample_array_2 = np.array([[10,20],[50,60]])

In [21]:
sample_array_2

array([[10, 20],
       [50, 60]])

In [23]:
# 3D Tensor (2 matrices , each with 2 rows and 2 column)

In [25]:
sample_tensor_3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [26]:
sample_tensor_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [27]:
sample_tensor_3 = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])

In [28]:
sample_tensor_3

array([[[10, 20],
        [30, 40]],

       [[50, 60],
        [70, 80]]])

In [29]:
# Dimensions 

In [31]:
# 0-D Array = Scalar ( 5 )

# 1-D Array = Vector ( [1,2,3,4,5] )

# 2-D Array = Matrix ( rows and columns )

# 3-D Array = Tensor ( page , rows , column  )


In [32]:
# Array properties 

In [33]:
sample_array = np.array([[1,2,3],[4,5,6]])

In [34]:
sample_array

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
# shape 

In [36]:
sample_array.shape

(2, 3)

In [37]:
# dimensios

In [38]:
sample_array.ndim

2

In [39]:
# total elements 

In [40]:
sample_array.size

6

In [41]:
# data type 

In [42]:
sample_array.dtype

dtype('int64')

In [46]:
sample_array_3 = np.array([[[10,20],[30,40]],[[50,60],[70,80]]])

In [47]:
sample_array_3

array([[[10, 20],
        [30, 40]],

       [[50, 60],
        [70, 80]]])

In [48]:
sample_array_3.shape

(2, 2, 2)

In [49]:
sample_array_3.ndim

3

In [50]:
sample_array_3.size

8

In [51]:
sample_array_3.dtype

dtype('int64')

In [52]:
# special array

In [53]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [55]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [57]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [59]:
np.arange(0,50,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [60]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [61]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [62]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [71]:
# indexing 

In [64]:
sample_array = np.array([10,20,30,40])

In [65]:
sample_array

array([10, 20, 30, 40])

In [66]:
sample_array[0]

np.int64(10)

In [67]:
sample_array[1]

np.int64(20)

In [68]:
sample_array[-1]

np.int64(40)

In [69]:
sample_array[-2]

np.int64(30)

In [70]:
# slicing 

In [72]:
sample_array[1:3]

array([20, 30])

In [73]:
# Array Operations 

In [74]:
a = np.array([1,2,3])

In [75]:
b = np.array([4,5,6])

In [76]:
a

array([1, 2, 3])

In [77]:
b

array([4, 5, 6])

In [78]:
a + b

array([5, 7, 9])

In [79]:
a - b

array([-3, -3, -3])

In [80]:
a * b

array([ 4, 10, 18])

In [81]:
a / b

array([0.25, 0.4 , 0.5 ])

In [82]:
a  = np.array([34,56,32])

In [83]:
b = np.array([89,77,29])

In [85]:
a 


array([34, 56, 32])

In [86]:
b

array([89, 77, 29])

In [87]:
a + b

array([123, 133,  61])

In [88]:
a - b

array([-55, -21,   3])

In [89]:
a * b

array([3026, 4312,  928])

In [90]:
a / b

array([0.38202247, 0.72727273, 1.10344828])

In [91]:
# mathematical functions 

In [99]:
sample_array = np.array([1,4,9])

In [100]:
sample_array

array([1, 4, 9])

In [101]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [102]:
sample_array1 = np.array([16,25,225,49])

In [103]:
np.sqrt(sample_array1)

array([ 4.,  5., 15.,  7.])

In [104]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [105]:
np.log(sample_array)

array([0.        , 1.38629436, 2.19722458])

In [106]:
# statistical functions

In [112]:
sample_array = np.array([1,2,3,4,5])

In [113]:
sample_array

array([1, 2, 3, 4, 5])

In [114]:
np.mean(sample_array)

np.float64(3.0)

In [116]:
np.median(sample_array)

np.float64(3.0)

In [117]:
np.std(sample_array)

np.float64(1.4142135623730951)

In [118]:
np.min(sample_array)

np.int64(1)

In [119]:
np.max(sample_array)

np.int64(5)

In [120]:
# reshaping array

In [125]:
 arr = np.arange(6)

In [126]:
arr

array([0, 1, 2, 3, 4, 5])

In [128]:
reshape = arr.reshape(2,3)

In [129]:
reshape

array([[0, 1, 2],
       [3, 4, 5]])

In [130]:
# flattening 

In [131]:
arr2 = np.array([[1,2],[3,4]])

In [132]:
arr2

array([[1, 2],
       [3, 4]])

In [133]:
arr2.flatten()

array([1, 2, 3, 4])

In [134]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [135]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [136]:
arr3.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [137]:
# joining arrays 

In [138]:
arr1 = np.array([1,2,3,4,5])

In [139]:
arr2 = np.array([6,7,8,9,10])

In [140]:
arr1

array([1, 2, 3, 4, 5])

In [141]:
arr2

array([ 6,  7,  8,  9, 10])

In [142]:
np.concatenate((arr1,arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [144]:
np.concat((arr1,arr2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [145]:
# splitting array

In [146]:
sample_array = np.array([1,2,3,4])

In [147]:
sample_array

array([1, 2, 3, 4])

In [149]:
np.array_split(sample_array , 2)

[array([1, 2]), array([3, 4])]

In [150]:
np.split(sample_array , 2)

[array([1, 2]), array([3, 4])]

In [151]:
# axis concept 

In [152]:
sample_array = np.array([[1,2],[3,4]])

In [153]:
np.sum(sample_array , axis= 0)

array([4, 6])

In [154]:
np.sum(sample_array , axis = 1)

array([3, 7])

In [155]:
# Nan & missing value

In [157]:
sample_array = np.array([1,np.nan,3])

In [158]:
sample_array

array([ 1., nan,  3.])

In [159]:
np.isnan(sample_array)

array([False,  True, False])

In [160]:
# random 

In [161]:
np.random.rand(3)

array([0.68448516, 0.1267359 , 0.36936999])

In [162]:
np.random.randint(1,10,5)

array([7, 8, 9, 5, 6], dtype=int32)

In [163]:
# create 2 numpy arrays and perform element wise addition ,substraction , multiplication and modulus operation 

In [164]:
arr1 = np.array([34,56,78,90,12])

In [166]:
arr2 = np.array([53,45,22,70,65])

In [167]:
arr1

array([34, 56, 78, 90, 12])

In [168]:
arr2

array([53, 45, 22, 70, 65])

In [169]:
arr1 + arr2

array([ 87, 101, 100, 160,  77])

In [173]:
arr1 -arr2

array([-19,  11,  56,  20, -53])

In [171]:
arr1 * arr2

array([1802, 2520, 1716, 6300,  780])

In [172]:
arr1 % arr2

array([34, 11, 12, 20, 12])